# Generated by Django 5.0 on 2023-12-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="special_post",
            field=models.BooleanField(default=False),
        ),
    ]
