# Generated by Django 5.0 on 2023-12-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0004_post_special_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=100)),
                ("time", models.DateField()),
            ],
        ),
    ]
