# Generated by Django 5.0 on 2023-12-31 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0005_update"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Update",
            new_name="News",
        ),
    ]
