# Generated by Django 5.0 on 2024-01-01 02:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0007_alter_news_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True, null=True, populate_from="title", unique=True
            ),
        ),
    ]
