# Generated by Django 5.0 on 2024-01-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0010_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
