# Generated by Django 5.0 on 2024-01-01 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0011_alter_post_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="author",
        ),
    ]
