# Generated by Django 5.0 on 2024-01-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0014_alter_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="%Y-%m-%d")),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ManyToManyField(blank=True, to="blogapp.image"),
        ),
    ]
