# Generated by Django 5.0 on 2024-01-02 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0015_image_remove_post_image_post_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="image",
            new_name="images",
        ),
    ]
